#lang ivy1.7
include quic_server_test
#
# Restrict generation to packets from the designated client endpoints
# to the server endpoint.
#

#   Token Length:  A variable-length integer specifying the length of the
#      Token field, in bytes.  This value is zero if no token is present.
#      Initial packets sent by the server MUST set the Token Length field
#      to zero; clients that receive an Initial packet with a non-zero
#      Token Length field MUST either discard the packet or generate a
#      connection error of type PROTOCOL_VIOLATION.

before packet_event(src:ip.endpoint,dst:ip.endpoint,pkt:quic_packet) {
    if _generating {
        require src = client.ep | src = client_alt;
        require dst = server.ep;
        require pkt.token.end = 1; # [1]
    };
    require pkt.long -> pkt.pversion = 0xff00001b  #version 27
}