#lang ivy1.7

include order
include quic_connection
include quic_infer
include file
include quic_shim
include quic_locale
include quic_server
include quic_fsm_sending
include quic_fsm_receiving


after frame.ack.handle(f:frame.ack,scid:cid,dcid:cid) {
    if _generating {
        call handle_sending_ack(f.largest_acked);
    } 
}

after frame.rst_stream.handle(f:frame.rst_stream,scid:cid,dcid:cid,seq_num:pkt_num) {
    if _generating {
        call handle_receiving_resetRecvd(f.id,seq_num);
    } 
}

after frame.stream.handle(f:frame.stream,scid:cid,dcid:cid,seq_num:pkt_num) {
    if _generating {
        if f.fin {
            call handle_receiving_sizeKnown(f.id,seq_num);
        } else {
            call handle_receiving_recv(f.id,seq_num);
        };
    } 
}

before frame.stream_data_blocked.handle(f:frame.stream_data_blocked,scid:cid,dcid:cid,seq_num:pkt_num) {
    if _generating {
        call handle_receiving_recv(f.id,seq_num);
    } 
}