#lang ivy1.7

include quic_client_test

# Upon receiving the client's Initial packet, the server can request address validation 
# by sending a Retry packet (Section 17.2.5) containing a token. This token MUST be 
# repeated by the client in all Initial packets it sends for that connection after it 
# receives the Retry packet.

# We send Retry packet and check in quic_packet if the corresponding requirement is make_transport_parameters

 # Not finished TODO